### ISSUE TITLE
ERROR: Net 'etherbone_rst' is multiply driven by cell ports FD1S3BX_1.Q and FD1S3BX_3.Q

### ISSUE THREAD

**Issue by jurkov** [enjoy-digital/colorlite#4]
Today i followed the guide from http://www.fabienm.eu/flf/15-ecp5-board-kit/ to setup yosys and next-pnr. The blinking example is working. Later i continued with this project.

I used .`/colorlite.py --build` to build everything. But i get the following error:
```
3.51. Executing CHECK pass (checking for obvious problems).
checking module colorlite..
Warning: multiple conflicting drivers for colorlite.\sys_rst:
    port Q[0] of cell FD1S3BX_1 (TRELLIS_FF)
    port Q[0] of cell FD1S3BX_3 (TRELLIS_FF)
found and reported 1 problems.

3.52. Executing JSON backend.

Warnings: 2 unique messages, 2 total
End of script. Logfile hash: ab23295401, CPU: user 20.76s system 0.13s, MEM: 335.69 MB peak
Yosys 0.9+3565 (git sha1 da3002e5, clang  -fPIC -Os)
Time spent: 20% 34x opt_clean (4 sec), 14% 32x opt_expr (3 sec), ...
ERROR: Net 'etherbone_rst' is multiply driven by cell ports FD1S3BX_1.Q and FD1S3BX_3.Q
0 warnings, 1 error
Traceback (most recent call last):
  File "./colorlite.py", line 133, in <module>
    main()
  File "./colorlite.py", line 120, in main
    builder.build(build_name="colorlite", run=args.build)
  File "/home/xxx/liteX/litex/litex/soc/integration/builder.py", line 214, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/home/xxx/liteX/litex/litex/soc/integration/soc.py", line 1048, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/xxx/liteX/litex/litex/build/lattice/platform.py", line 39, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/xxx/liteX/litex/litex/build/lattice/trellis.py", line 234, in build
    _run_script(script)
  File "/home/xxx/liteX/litex/litex/build/lattice/trellis.py", line 164, in _run_script
    raise OSError("Subprocess failed")
OSError: Subprocess failed
```
Do you know how i can fix this problem?

**Comment by jurkov** [comment]
I got it working by removing Line 50 from colorlite.py

**Comment by enjoy-digital** [comment]
Thanks @jurkov for the feedback, the design indeed had to be updated, which has been done with https://github.com/enjoy-digital/colorlite/commit/b52aa387910a50932ddb29325eb16e1ab3c598b6.
